MT-0002 Init commit
pilivpp/ApexAdventures pull request #2
Opened 2024-05-19 20:31 UTC by pilivpp

2024-05-24 09:56 UTC, JuliuszGasecki requested changes
[MAJOR]
Brakuje wywołania lwc
[MAJOR/DOUBT]
Gdzie się tworzy log?
[DOUBT]
TO nie miała być osadzone we flow?

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +
[MAJOR]
Integracje powinny mieć swoją klasę. Obłsuga request i response chociaż w osobnych metodach

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +        Http http = new Http();
[MAJOR]
Zawsze takie coś try catchujemy

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +        String endpoint = 'callout:Github/' + settings.Endpoint__c;
[MINOR]
Ten string albo do stałych w klasie albo do metadanych

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +            System.debug('HTTP Error: '+response.getStatusCode()+' '+response.getStatus());
[MAJOR]
Sam debug to niewystarczająca obsługa błędu. Zapisać w obiekcie log a najlepiej obsłużyć też to na froncie

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerCommitDetails/githubViewerCommitDetails.css
> +.commit-container {
[INFO]
Nie jestem CSSowym świrkiem, więc jeśli działa to git xD ale ciężko mi dać Ci jakiś super feedback

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerContainer/githubViewerContainer.html
> +        <div class="footer">
[INFO]
Rozważ użycie flowowych buttonów i przenoszenie stanu miedzy oknami

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerContainer/githubViewerContainer.js
> +    get listOfCommitsStage() {
[MAJOR/DOUBT]
Trochę niejasne te nazwy. Sugerują zwrotkę listy albo stage a to zwraca booleana

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerContainer/githubViewerContainer.js
> +    currentStage = 'listOfCommitsStage';
[MINOR]
Może podziałać z enumami, żeby ktoś w przyszłości nie dodał sobie jakiegoś dziwnego statusu z palca?

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.html
> +                message-when-value-missing="First, choose a commit to move to the next page.">
[MAJOR]
Teksty do labelek albo innej formy możliwej do zmiany z poziomu metadanych

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.js
> +    connectedCallback() {
[MAJOR/DOUBT]
To będzie uderzało do zewnętrznego systemu za każdym razem jak się wróci do listy commitów? Zadbajmy o limity API calls. Niech to się zaciąga tylko raz w czasie życia komponentu

2024-05-24 09:56 UTC, JuliuszGasecki commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.js
> +            this.commits = JSON.parse(response);
[MAJOR/DOUBT]
Obsługę deserializacji można zostawić po stronie apexa dając możliwość reużywalności tamtego kodu. Wtedy można z backendu przekazać tylko gotowy wrapper.

2024-05-24 09:57 UTC, JuliuszGasecki commented on force-app/main/default/customMetadata/APISettings.GitHubEndpoint.md-meta.xml
> +        <value xsi:type="xsd:string">repos/pilivpp/ApexAdventures/commits?sha=MT-0001</value>
[MAJOR]
NIe wiem czy to najlepszy pomysł trzymać w repo endpointy. Zrób MSa który tworzy ręcznie ten obiekt w systemie

2024-05-24 13:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +
1. Klasa do integracji
2. Klasa kontroler

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +
3. Napisać oddzielne metody dla tworzenia requestu i odbierania response

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +        Http http = new Http();
1. Utwórz try catch dla tworzenia response

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +        Http http = new Http();
2. Doczytać o AuraException

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +        String endpoint = 'callout:Github/' + settings.Endpoint__c;
1. Wrzuć do zmiennej stałej w klasie

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +            System.debug('HTTP Error: '+response.getStatusCode()+' '+response.getStatus());
Zapisz w obiekcie log

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/customMetadata/APISettings.GitHubEndpoint.md-meta.xml
> +        <value xsi:type="xsd:string">repos/pilivpp/ApexAdventures/commits?sha=MT-0001</value>
1. Stwórz folder z manual stepami

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/customMetadata/APISettings.GitHubEndpoint.md-meta.xml
> +        <value xsi:type="xsd:string">repos/pilivpp/ApexAdventures/commits?sha=MT-0001</value>
* Na różnych środowiskach mogłyby być różne endpoint'y - argument za przeniesieniem

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerContainer/githubViewerContainer.html
> +        <div class="footer">
Inne podejście

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerContainer/githubViewerContainer.js
> +    currentStage = 'listOfCommitsStage';
1. Na razie stwórz na enumie

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerContainer/githubViewerContainer.js
> +    get listOfCommitsStage() {
1. isCommitsStage

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.html
> +                message-when-value-missing="First, choose a commit to move to the next page.">
1. Po mergu brancha

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.js
> +    connectedCallback() {
1. Dane się cacheują

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.js
> +            this.commits = JSON.parse(response);
1. Zrób wrappera

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/classes/GitHubCommitsHandler.cls
> +
4. Dorób tworzenia Case

2024-08-16 18:18 UTC, pilivpp commented on force-app/main/default/lwc/githubViewerListOfCommits/githubViewerListOfCommits.js
> +            this.commits = JSON.parse(response);
W tym przypadku nie ma to sensu bo była by mnoga ilość wraperrów przez ilość zagnieżdżeń w odpowiedzi od GitHub

2024-08-16 18:18 UTC, merged